# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2
phases:
  install:
    commands:
      - echo Entered the install phase...
      - curl -fsSL https://deb.nodesource.com/setup_14.x | bash -
      - apt install -y nodejs

  pre_build:
    commands:
      #installs dependencies into the node_modules/ directory
      - npm install 
      
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
      # - rm -r node_modules
# Include only the files required for your application to run.
artifacts:
  files:
    # - public/**/*
    # - src/**/*
    # - package.json
    # - appspec.yml
    # - scripts/**/*
    # - middleware/**/*
    # - db/**/*
    # - config/**/*
    # - server.js
    - "**/*"